// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCSBYViWH54e-bRsUKA78r7FHwE0zqSE',
    appId: '1:350783776087:web:48118e09da50bb6f018a12',
    messagingSenderId: '350783776087',
    projectId: 'iu-ca-7ed4d',
    authDomain: 'iu-ca-7ed4d.firebaseapp.com',
    storageBucket: 'iu-ca-7ed4d.appspot.com',
    measurementId: 'G-QD14BCP2F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSLVPgKWjjnn3TlqIwYz_gpqIa7IWHws',
    appId: '1:350783776087:android:f0da7c78e0aa591c018a12',
    messagingSenderId: '350783776087',
    projectId: 'iu-ca-7ed4d',
    storageBucket: 'iu-ca-7ed4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQymhjkvYmxicIKTNUXvE1e28N8WrfJM',
    appId: '1:350783776087:ios:0ac92c3ef44b98d1018a12',
    messagingSenderId: '350783776087',
    projectId: 'iu-ca-7ed4d',
    storageBucket: 'iu-ca-7ed4d.appspot.com',
    iosClientId: '350783776087-r6iodogsu6r1hep8hpj0cj18iu8uptmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.iuCa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUQymhjkvYmxicIKTNUXvE1e28N8WrfJM',
    appId: '1:350783776087:ios:067895a8676de3cc018a12',
    messagingSenderId: '350783776087',
    projectId: 'iu-ca-7ed4d',
    storageBucket: 'iu-ca-7ed4d.appspot.com',
    iosClientId: '350783776087-926m5go5om2osn5q16n3eltfo06j1nj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.iuCa.RunnerTests',
  );
}
